name: Build and deploy ASP.Net Core app to Azure Web App - api-estudiantes-leanny-2026

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore API
        run: dotnet restore ./ApiEstudiantes.csproj

      - name: Build API
        run: dotnet build ./ApiEstudiantes.csproj --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish ./ApiEstudiantes.csproj --configuration Release --no-restore --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-estudiantes
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-estudiantes

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_54F08A84B78348C8A2E1ACB7168822DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4517AF396F394A49B56A18FE7E8DC0C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CDF31C70C1D24E02BEDEFEDFCF7CA830 }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: api-estudiantes-leanny-2026
          slot-name: Production
          package: .


